# -*- coding: utf-8 -*-
"""YOLO_v8n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0d-kqNrTpCmwR4UdvG1OdNmfM5BDkL2

#**Projeto 01 - Introdução ao Aprendizado de Máquina Profundo (MS671)**

- Gustavo Coimbra de Souza Teixeira - RA: 237599
- Julia Folgueral - RA: 277178
- Luiz Fernando de Oliveira Pereira - RA: 267356
- Maria Eduarda Villéla Silva - RA: 212974

# Reconhecimento de Objetos com YOLOv8 (PyTorch)

Este notebook apresenta uma implementação de detecção de objetos baseada na arquitetura **YOLOv8-nano**, reconstruída em PyTorch.
Os pesos pré-treinados são carregados a partir do arquivo `.pt oficial`, sem utilizar as funções da biblioteca Ultralytics.

Note que as funções abaixo foram implementadas manualmente, conforme solicitado:
- `manual_iou()` — cálculo da Intersecção Sobre a União
- `manual_nms()` — Supressão Não-Maximal

## 1. Montar o github e instalar dependências
"""

# Commented out IPython magic to ensure Python compatibility.
# Acessos para o githb das fotos e do yolo.v8
import os

# Clona o repositório do projeto
!git clone https://github.com/onorario/YOLO-MS671-Projeto.git

# Entra dentro da pasta do repositório que foi clonado
# %cd YOLO-MS671-Projeto

# Download dos pesos pré-treinados do YOLOv8 (versão nano)
if not os.path.exists('yolov8n.pt'):
    !wget https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt

# Confirmação e listagem dos arquivos disponíveis no diretório (para ter certeza que funcionou)
print("\nAmbiente configurado com sucesso! Arquivos disponíveis:")
!ls

# Instala pacotes necessários para o projeto:
# - torch / torchvision: construção e execução do modelo
# - pillow: manipulação de imagens
# - matplotlib: visualização de resultados
# - numpy: operações numéricas
!pip install -q torch torchvision pillow matplotlib numpy

# Baixa os pesos pré-treinados do YOLOv8-nano diretamente do repositório da Ultralytics.
# Note que aqui usamos apenas o arquivo de pesos (.pt), sem utilizar a biblioteca Ultralytics para carregar o modelo pronto!
import urllib.request, os

WEIGHTS_URL = "https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt"
WEIGHTS_PATH = "yolov8n.pt"

if not os.path.exists(WEIGHTS_PATH):
    print("Baixando yolov8n.pt...")
    urllib.request.urlretrieve(WEIGHTS_URL, WEIGHTS_PATH)
    print(f"Download concluído: {os.path.getsize(WEIGHTS_PATH)/1e6:.1f} MB")
else:
    print("Arquivo de pesos já existe.")

import urllib.request, os

# Baixa o arquivo com os nomes das classes do dataset COCO (ex: pessoa, carro, cachorro, etc.)
# O arquivo coco.names mapeia os índices previstos pelo modelo para nomes de categorias
COCO_URL = "https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names"
if not os.path.exists("coco.names"):
    urllib.request.urlretrieve(COCO_URL, "coco.names")
    print("coco.names baixado.")

"""## 2. Arquitetura YOLOv8 — Implementação

O YOLOv8 é composto por três partes principais, sendo elas:
1. Extração de características da imagem (como bordas, formas e padrões mais complexos).
2. Combinação dessas informações em diferentes escalas, permitindo detectar tanto objetos pequenos quanto grandes.
3. Uso dessas features para prever onde estão os objetos (bounding boxes) e quais são suas classes.

### Diferença principal em relação ao YOLOv3:
- Uso de blocos mais modernos (C2f) no lugar dos blocos residuais antigos, melhorando a extração de características.
- As caixas não são previstas diretamente, o modelo estima uma distribuição de possíveis posições (DFL) e calcula o valor final a partir dela, o que aumenta a precisão.
- A saída é desacoplada, ou seja, uma parte do modelo prevê a presença de objeto, enquanto outra prevê a classe, tornando o processo mais eficiente.
"""

# Carregando pacotes necessários
# - construção do modelo (torch)
# - operações matemáticas (numpy, math)
# - visualização (matplotlib)
# - manipulação de imagens (PIL)
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image, ImageDraw, ImageFont
import colorsys, random, math

# Implementando a arquitetura - blocos fundamentais da arquitetura YOLOv8 em PyTorch, incluindo as camadas convolucionais,
# blocos residuais, o módulo principal (C2f), uma camada de agregação de contexto (SPPF) e o mecanismo de decodificação das bounding boxes (DFL).

class Conv(nn.Module):

    """
    Bloco base do YOLOv8: Convolução  -> BatchNorm2d -> ativação (SiLU)
    Nota: O v8 usa SiLU (Sigmoid Linear Unit) em vez do LeakyReLU do v3.
    SiLU(x) = x * sigmoid(x) — A ativação SiLU é mais suave que ReLU/LeakyReLU e melhora o aprendizado..
    """
    def __init__(self, in_c, out_c, k=1, s=1, p=None, g=1):
        super().__init__()
        # Define padding automático para manter o tamanho da imagem
        if p is None:
            p = k // 2
        self.conv = nn.Conv2d(in_c, out_c, k, s, p, groups=g, bias=False)
        self.bn   = nn.BatchNorm2d(out_c, eps=1e-3, momentum=0.03)
        self.act  = nn.SiLU(inplace=True)

    def forward(self, x):
        return self.act(self.bn(self.conv(x)))


class Bottleneck(nn.Module):
    """
    Bottleneck do YOLOv8: duas convoluções 3x3 com conexão residual opcional (skip connection).
    Diferente do v3 (que usava 1x1 -> 3x3), o v8 usa 3x3 -> 3x3, evitando perda de gradiente.
    """
    def __init__(self, in_c, out_c, shortcut=True, e=0.5):
        super().__init__()
        hidden = int(out_c * e)
        self.cv1 = Conv(in_c,   hidden, 3, 1)
        self.cv2 = Conv(hidden, out_c,  3, 1)
        # Só usa conexão residual se entrada e saída tiverem mesmo tamanho
        self.add = shortcut and (in_c == out_c)

    def forward(self, x):
        return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))


class C2f(nn.Module):
    """
    Bloco principal do YOLOv8.

    - Divide a informação em dois caminhos após uma convolução 1x1
    - Um deles passa por vários Bottlenecks e o resultado d ecada um é guardado
    - Junta tudo no final com uma convolução 1x1

    Isso melhora o fluxo de informação e reduz custo computacional.
    """

    def __init__(self, in_c, out_c, n=1, shortcut=True, e=0.5):
        super().__init__()
        hidden = int(out_c * e)
        self.cv1 = Conv(in_c,       2 * hidden, 1, 1)
        self.cv2 = Conv((2 + n) * hidden, out_c, 1, 1)
        # Sequência de bottlenecks
        self.m   = nn.ModuleList(
            [Bottleneck(hidden, hidden, shortcut, e=1.0) for _ in range(n)]
        )

    def forward(self, x):
        # # Divide o tensor em dois caminhos
        y = list(self.cv1(x).chunk(2, dim=1))
        # Aplica bottlenecks em sequência
        y.extend(m(y[-1]) for m in self.m)
        # Concatena todos e reduz dimensões
        return self.cv2(torch.cat(y, dim=1))


class SPPF(nn.Module):
    """
    Camada que aumenta o "campo de visão" da rede.
    Captura contexto global aplicando MaxPool de tamanho k três vezes
    sequencialmente
    (entende melhor a imagem como um todo)
    """
    def __init__(self, in_c, out_c, k=5):
        super().__init__()
        hidden = in_c // 2
        self.cv1 = Conv(in_c,      hidden, 1, 1)
        self.cv2 = Conv(hidden * 4, out_c, 1, 1)
        self.m   = nn.MaxPool2d(k, stride=1, padding=k // 2)

    def forward(self, x):
        x  = self.cv1(x)
        y1 = self.m(x)
        y2 = self.m(y1)
        return self.cv2(torch.cat([x, y1, y2, self.m(y2)], dim=1))


class DFL(nn.Module):
    """
    Camada de decodificação das caixas:
    Converte a saída do modelo em coordenadas de bounding boxes.
    Em vez de prever diretamente os valores das caixas,
    o modelo prevê distribuições de probabilidade.

    Aqui transformamos essas distribuições em valores finais
    usando o valor esperado.
    Isso é equivalente a uma conv 1x1 com pesos fixos [0, 1, ..., reg_max-1]
    aplicada após o softmax
    """

    def __init__(self, reg_max=16):
        super().__init__()
        self.reg_max = reg_max
        # Pesos fixos: [0, 1, 2, ..., reg_max-1]
        # Não queremos que esses pesos sejam treinados.
        self.conv = nn.Conv2d(reg_max, 1, 1, bias=False)
        self.conv.weight.data = torch.arange(
            reg_max, dtype=torch.float32
        ).reshape(1, reg_max, 1, 1)
        self.conv.weight.requires_grad_(False)

    def forward(self, x):
        B, C, H, W = x.shape
        # Separa as 4 distribuições (top, bottom, left, right)
        x = x.view(B, 4, self.reg_max, H * W)
        x = x.permute(0, 3, 1, 2)
        x = F.softmax(x, dim=-1)
        x = x.permute(0, 2, 3, 1)
        x = x.reshape(B * 4, self.reg_max, 1, H * W)
        # Calcula valor esperado --> coordenada final
        return self.conv(x).reshape(B, 4, H * W)

"""No chunck abaixo, os blocos implementados anteriormente são conectados e é montada a arquitetura completa do YOLOv8-nano, definindo o fluxo de dados desde a imagem de entrada até as previsões finais."""

class DetectHead(nn.Module):
    """
    Detecção do YOLO:

    Para cada escala da imagem, o modelo prevê:
    - caixas (bounding boxes)
    - classes dos objetos

    Diferenças importantes:
    - Regressão (caixas) e classificação são feitas em ramos separados
    - Não há "objectness score", a confiança final é só a probabilidade de classe
    - As caixas são previstas via distribuição, não diretamente (por coordenadas)
    """

    def __init__(self, num_classes=80, ch=()):  # ch = canais de entrada de cada escala
        super().__init__()
        self.nc       = num_classes
        self.reg_max  = 16
        self.no       = num_classes + self.reg_max * 4
        self.nl       = len(ch)        # número de escalas (3)
        self.stride   = torch.zeros(self.nl)

        # Define número de canais internos dos ramos
        reg_ch = max(16, self.reg_max * 4, ch[0] // 4)
        cls_ch = max(num_classes, ch[0])

        # Previsão das caixas
        self.cv2 = nn.ModuleList(
            nn.Sequential(Conv(c, reg_ch, 3), Conv(reg_ch, reg_ch, 3),
                          nn.Conv2d(reg_ch, 4 * self.reg_max, 1)) for c in ch
        )
        # Previsão das classes
        self.cv3 = nn.ModuleList(
            nn.Sequential(Conv(c, cls_ch, 3), Conv(cls_ch, cls_ch, 3),
                          nn.Conv2d(cls_ch, num_classes, 1)) for c in ch
        )
        self.dfl = DFL(self.reg_max)

    def forward(self, feats):
        # Para cada escala, gera: features de caixa e features de classe
        outputs = []
        for i, x in enumerate(feats):
            box_feat = self.cv2[i](x)
            cls_feat = self.cv3[i](x)
            outputs.append((box_feat, cls_feat))
        return outputs


class YOLOv8n(nn.Module):
    """
    Implementação completa do YOLOv8-nano.

    O modelo é dividido em:
    - Backbone: extrai características da imagem
    - Neck: combina informações em múltiplas escalas
    - Head: faz as previsões finais

    A versão "nano" é menor e mais leve (menos canais e menos camadas).
    """

    def __init__(self, num_classes=80):
        super().__init__()
        # Para nano: width=0.25, depth=0.33
        # Canais base: [64, 128, 256, 512] escalados por 0.25 = [16, 32, 64, 128]
        # Repetições base: [3, 6, 6, 3] escaladas por 0.33 = [1, 2, 2, 1]

        # Extração de features (backbone)
        self.model = nn.Sequential(
            # Entrada 3ch --> 16ch
            Conv(3, 16, 3, 2), # reduz a resolução pela metade
            Conv(16, 32, 3, 2),  # reduz novamente
            C2f(32, 32, n=1, shortcut=True),

            Conv(32, 64, 3, 2), # objetos pequenos
            C2f(64, 64, n=2, shortcut=True),

            Conv(64, 128, 3, 2), # objetos médios
            C2f(128, 128, n=2, shortcut=True),

            Conv(128, 256, 3, 2), # objetos grandes
            C2f(256, 256, n=1, shortcut=True),

            SPPF(256, 256, k=5), # contexto global
        )

        # Combinação de escalas (neck)
        # de features profundas para rasas (top-down)
        self.up1  = nn.Upsample(scale_factor=2, mode='nearest')
        self.c2f_p4_td = C2f(256 + 128, 128, n=1, shortcut=False)

        self.up2  = nn.Upsample(scale_factor=2, mode='nearest')
        self.c2f_p3_td = C2f(128 + 64, 64, n=1, shortcut=False)

        # refinamento (bottom-up)
        self.down1     = Conv(64, 64, 3, 2)
        self.c2f_p4_bu = C2f(64 + 128, 128, n=1, shortcut=False)

        self.down2     = Conv(128, 128, 3, 2)                     # P4 40->20
        self.c2f_p5_bu = C2f(128 + 256, 256, n=1, shortcut=False)

        # previsões finais
        self.head = DetectHead(num_classes, ch=(64, 128, 256))

    def forward(self, x):
        # Backbone
        for i, layer in enumerate(self.model):
            x = layer(x)
            # Salvamos três níveis de feature maps
            if i == 4:  p3 = x   # 80x80, 64ch
            if i == 6:  p4 = x   # 40x40, 128ch
            if i == 9:  p5 = x   # 20x20, 256ch  (após SPPF)

        # Neck top-down
        x      = self.up1(p5)                           # 40x40
        x      = self.c2f_p4_td(torch.cat([x, p4], 1)) # funde com P4
        p4_out = x                                       # salva para bottom-up

        x      = self.up2(x)                            # 80x80
        x      = self.c2f_p3_td(torch.cat([x, p3], 1)) # funde com P3
        p3_out = x                                       # saída P3 do neck

        # Neck bottom-up
        x      = self.down1(p3_out)                          # 40x40
        x      = self.c2f_p4_bu(torch.cat([x, p4_out], 1))  # funde com P4
        p4_fin = x

        x      = self.down2(p4_fin)                          # 20x20
        p5_fin = self.c2f_p5_bu(torch.cat([x, p5], 1))      # funde com P5

        # Head
        return self.head([p3_out, p4_fin, p5_fin])

"""## 3. Carregamento dos Pesos do YOLOv8

O arquivo `.pt` salvo pela Ultralytics contém um modelo Python completo (não apenas pesos). Vamos organizá-los em um dicionário para podermos reutilizá-los na nossa implementação (queremos mapear os pesos para usar na nossa arquitetura manualmente).
"""

# Carregando a biblioteca
!pip install ultralytics

def inspecionar_pesos(caminho_pt):
    """
    Carrega e inspeciona o arquivo .pt do YOLOv8.

    Objetivo:
    - Entender o que existe dentro do arquivo
    - Extrair os pesos (state_dict) do modelo da Ultralytics
    - Visualizar nomes e dimensões das camadas
    """

    # Carrega o arquivo .pt
    # map_location='cpu' garante que tudo será carregado na CPU
    # weights_only=False permite acessar o objeto completo (não só pesos)
    ckpt = torch.load(caminho_pt, map_location='cpu', weights_only=False)
    print("Chaves no checkpoint:", list(ckpt.keys()))

    # O modelo treinado está armazenado em ckpt['model']
    # Esse é um objeto Python da biblioteca Ultralytics
    modelo_ultra = ckpt['model']
    state = modelo_ultra.state_dict()

    print(f"\nTotal de tensores no state_dict: {len(state)}")
    print("\nPrimeiras 20 chaves:")
    # Mostra alguns exemplos de camadas:
    # - nome da camada
    # - formato do tensor (dimensão dos pesos)
    for k in list(state.keys())[:20]:
        print(f"  {k:60s} {tuple(state[k].shape)}")
    return state

state_ultra = inspecionar_pesos("yolov8n.pt") # Executa a função e armazena os pesos do YOLOv8

"""Agora, vamos fazer o mapeamento dos pesos do modelo original da Ultralytics para a nossa implementação, ajustando os nomes das camadas para que sejam compatíveis e carregando esses pesos manualmente"""

def carregar_pesos_yolov8(caminho_pt, modelo):

    """
    Carrega os pesos do modelo YOLOv8 oficial (Ultralytics)
    para a nossa implementação manual em PyTorch.

    Como as duas implementações têm nomes diferentes para as camadas,
    precisamos mapear manualmente esses nomes.
    """
    # Carrega o checkpoint completo
    ckpt  = torch.load(caminho_pt, map_location='cpu', weights_only=False)
    # Extrai apenas os pesos do modelo original
    src   = ckpt['model'].state_dict()

    # Mapeamento dos nomes das camadas: nome_ultralytics -> nome_no_nosso_modelo
    mapa = {
        # BACKBONE
        'model.0.':  'model.0.',
        'model.1.':  'model.1.',
        'model.2.':  'model.2.',
        'model.3.':  'model.3.',
        'model.4.':  'model.4.',
        'model.5.':  'model.5.',
        'model.6.':  'model.6.',
        'model.7.':  'model.7.',
        'model.8.':  'model.8.',
        'model.9.':  'model.9.',
        # NECK top-down
        'model.12.': 'c2f_p4_td.',
        'model.15.': 'c2f_p3_td.',
        # NECK bottom-up
        'model.16.': 'down1.',
        'model.18.': 'c2f_p4_bu.',
        'model.19.': 'down2.',
        'model.21.': 'c2f_p5_bu.',
        # HEAD
        'model.22.cv2.': 'head.cv2.', # caixas
        'model.22.cv3.': 'head.cv3.', # classe
        'model.22.dfl.': 'head.dfl.', # distribuição
    }

    dst = {} # novo dicionário com nomes compatíveis com nosso modelo
    nao_mapeado = []  # lista de pesos que não conseguimos mapear

    # Percorre todos os pesos do modelo original
    for k_src, v in src.items():
        k_dst = None
        for prefixo_src, prefixo_dst in mapa.items():
            if k_src.startswith(prefixo_src):
              # Substitui o prefixo pelo equivalente no nosso modelo
                k_dst = k_src.replace(prefixo_src, prefixo_dst, 1)
                break

        # Se conseguiu mapear, adiciona ao novo dicionário. Caso contrário, guarda como não mapeado.
        if k_dst is not None:
            dst[k_dst] = v
        else:
            nao_mapeado.append(k_src)

    # Carregar os pesos no nosso modelo:
    # strict=False permite carregar parcialmente (caso algo não bata exatamente)
    resultado = modelo.load_state_dict(dst, strict=False)
    print(f"Pesos carregados: {len(dst)}/{len(src)}")

    # Diagnóstico (para evitar bugs)
    # Pesos que o nosso modelo esperava mas não encontrou
    if resultado.missing_keys:
        print(f"  Faltando no nosso modelo ({len(resultado.missing_keys)}):")
        for k in resultado.missing_keys[:10]:
            print(f"    {k}")
    # Pesos que vieram mas não são usados no nosso modelo
    if resultado.unexpected_keys:
        print(f"  Inesperados ({len(resultado.unexpected_keys)}): (geralmente são strides/anchors internos)")
    # Pesos do modelo original que não conseguimos mapear
    if nao_mapeado:
        print(f"  Não mapeados do source ({len(nao_mapeado)}):")
        for k in nao_mapeado[:5]:
            print(f"    {k}")
    return modelo

# Preparação final do modelo
# Define se vai usar GPU ou CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Dispositivo: {device}")

# Finalmente, cria nosso modelo YOLOv8 do zero
modelo = YOLOv8n(num_classes=80).to(device)

# Carrega os pesos do modelo oficial nele
modelo = carregar_pesos_yolov8('yolov8n.pt', modelo)
modelo.eval()
print("\nModelo pronto!")

"""## 4. Pré-processamento de Imagens

Aqui é feita a implementação do pré-processamento das imagens, incluindo redimensionamento com preservação de proporção (letterbox), normalização e conversão para tensor, além da etapa inversa para mapear as bounding boxes de volta para a imagem original.
"""

def ler_classes(caminho):
  # Abre o arquivo com os nomes das classes (coco.names)
    with open(caminho) as f:
      # Remove espaços/quebras de linha e retorna lista de strings
        return [c.strip() for c in f.readlines()]

def gerar_cores(nomes_classes):
   # Cria cores distintas
    hsv = [(x / len(nomes_classes), 0.9, 0.9) for x in range(len(nomes_classes))]
    # Converte de HSV para RGB e escala para [0, 255]
    cores = [tuple(int(v*255) for v in colorsys.hsv_to_rgb(*h)) for h in hsv]
    # Embaralha as cores para evitar padrões previsíveis
    random.seed(42)
    random.shuffle(cores)
    return cores

def letterbox(image, novo_tamanho=(640, 640), cor=(114, 114, 114)):
    """
    Redimensiona a imagem mantendo a proporção original.
    O espaço restante é preenchido com a cor especificada (cinza neutro).
    Isso evita distorção geométrica que prejudicaria a detecção.
    """

    # Tamanho original
    iw, ih = image.size
    # Tamanho que queremos (ex: 640x640)
    nw, nh = novo_tamanho
    # Calcula escala mantendo proporção
    escala = min(nw / iw, nh / ih)
    # Novo tamanho redimensionado
    nw_r   = int(iw * escala)
    nh_r   = int(ih * escala)
    # Redimensiona a imagem
    img_r = image.resize((nw_r, nh_r), Image.BICUBIC)
    # Cria imagem com fundo cinza
    canvas = Image.new('RGB', novo_tamanho, cor)
    # Calcula onde colar a imagem (centralizada)
    offset_x = (novo_tamanho[0] - nw_r) // 2
    offset_y = (novo_tamanho[1] - nh_r) // 2
    # Cola a imagem redimensionada na imagem do fundo cinza
    canvas.paste(img_r, (offset_x, offset_y))
    return canvas, escala, offset_x, offset_y

def preprocessar(caminho_img, tamanho=640):
    """
    Etapas de pré-processamento da imagem:

    1. Carrega a imagem
    2. Aplica letterbox (redimensionamento + padding)
    3. Converte para array NumPy
    4. Normaliza
    5. Ajusta formato
    6. Converte para tensor PyTorch
    """
    # Carrega imagem original
    img_orig = Image.open(caminho_img).convert('RGB')
    # Aplica letterbox
    img_lb, escala, ox, oy = letterbox(img_orig, (tamanho, tamanho))
    # Converte para array e normaliza
    arr = np.array(img_lb, dtype=np.float32) / 255.0
    # Muda formato: altura/largura/canais --> canais/altura/largura
    arr = np.transpose(arr, (2, 0, 1))
     # Converte para tensor
    tensor = torch.from_numpy(arr).unsqueeze(0)

    return img_orig, tensor, escala, ox, oy

def reverter_caixas(boxes, escala, offset_x, offset_y, img_orig_size):
    """
    Converte as caixas previstas no espaço 640x640 (letterbox)
    de volta para o tamanho original da imagem.

    Passos:
    1. Remove o padding
    2. Desfaz a escala
    3. Garante que as caixas fiquem dentro da imagem
    """
    boxes = boxes.clone().float()
    # Remove deslocamento causado pelo padding
    boxes[:, [0, 2]] -= offset_x
    boxes[:, [1, 3]] -= offset_y
    # Desfaz a escala
    boxes /= escala
    # Limita coordenadas ao tamanho da imagem original
    iw, ih = img_orig_size
    boxes[:, [0, 2]] = boxes[:, [0, 2]].clamp(0, iw)
    boxes[:, [1, 3]] = boxes[:, [1, 3]].clamp(0, ih)
    return boxes
# Carrega nomes das classes (COCO)
class_names = ler_classes('coco.names')
# Gera uma cor para cada classe (para visualização)
CORES = gerar_cores(class_names)

print(f"{len(class_names)} classes carregadas. Exemplo: {class_names[:5]}")

"""## 5. Decoder das Saídas do YOLOv8

A saída do modelo para cada escala é um par `(box_feat, cls_feat)`.  
Precisamos converter isso para caixas absolutas em pixels.
"""

def gerar_grade(h, w, stride, device):
    """
    Gera a grade de pontos centrais da imagem.

    Cada ponto da grade representa o centro de uma possível detecção.
    No YOLOv8 não usamos âncoras fixas, usamos apenas esses pontos.
    """

    # Cria coordenadas (y, x) para cada posição da feature map
    gy, gx = torch.meshgrid(
        torch.arange(h, device=device),
        torch.arange(w, device=device),
        indexing='ij'
    )
    # Junta (x, y) em pares e transforma em lista
    grade = torch.stack([gx, gy], dim=-1).reshape(-1, 2).float()

    # Converte de "índice da grade" para coordenada em pixels
    # +0.5 leva do canto da célula para o centro
    return (grade + 0.5) * stride


def decodificar_saidas(outputs, img_size=640, device='cpu'):
    """
    Converte a saída bruta do modelo em bounding boxes de verdade.

    O modelo retorna:
    - distâncias em relação ao centro (via distribuição)
    - probabilidades de classe

    Aqui transformamos isso em:
    - caixas (x1, y1, x2, y2)
    - probabilidades por classe
    """
    # Stride = quanto cada célula da feature map representa na imagem original
    # Strides para cada escala: 8 (80x80), 16 (40x40), 32 (20x20)
    strides = [img_size // s for s in [80, 40, 20]]
    dfl = DFL(reg_max=16).to(device)

    todas_caixas  = []
    todas_classes = []

    for i, ((box_feat, cls_feat), stride) in enumerate(zip(outputs, strides)):
        B, _, H, W = box_feat.shape

        # Gerar grade de centros
        grade = gerar_grade(H, W, stride, device)

        # Decodifica DFL -> distâncias (dl, dt, dr, db)
        dist = dfl(box_feat).squeeze(0)
        dist = dist * stride

        # Converte para pixels reais
        dl, dt, dr, db = dist[0], dist[1], dist[2], dist[3]
        cx, cy = grade[:, 0], grade[:, 1]

        # Converte para caixas
        x1 = (cx - dl).unsqueeze(1)
        y1 = (cy - dt).unsqueeze(1)
        x2 = (cx + dr).unsqueeze(1)
        y2 = (cy + db).unsqueeze(1)
        caixas = torch.cat([x1, y1, x2, y2], dim=1)

        # Probabilidades de classe
        # YOLOv8 usa sigmoid (não softmax)
        classes = torch.sigmoid(cls_feat.squeeze(0).reshape(80, -1).T)

        todas_caixas.append(caixas)
        todas_classes.append(classes)

    # Junta todas as escalas
    todas_caixas  = torch.cat(todas_caixas,  dim=0)
    todas_classes = torch.cat(todas_classes, dim=0)

    return todas_caixas, todas_classes

"""## 6. Implementação manual do IoU e NMS

6.1. Implementação da Função manual_iou
"""

def manual_iou(box, boxes):
    """
    Calcula o IoU (Intersection over Union) entre uma caixa e várias outras.

    IoU = área da interseção / área da união

    Parâmetros:
    - box: tensor no formato [x1, y1, x2, y2]
    - boxes: tensor com várias caixas no mesmo formato
    """
    # 1. Determinar as coordenadas do retângulo de intersecção
    x1_inter = torch.max(box[0], boxes[:, 0])
    y1_inter = torch.max(box[1], boxes[:, 1])
    x2_inter = torch.min(box[2], boxes[:, 2])
    y2_inter = torch.min(box[3], boxes[:, 3])

    # 2. Calcular área da intersecção (clamp garante que não seja negativa se não houver sobreposição)
    inter_w = torch.clamp(x2_inter - x1_inter, min=0)
    inter_h = torch.clamp(y2_inter - y1_inter, min=0)
    area_intersecao = inter_w * inter_h

    # 3. Calcular áreas individuais
    area_box = (box[2] - box[0]) * (box[3] - box[1])
    area_boxes = (boxes[:, 2] - boxes[:, 0]) * (boxes[:, 3] - boxes[:, 1])

    # 4. Calcular União: Área1 + Área2 - Intersecção
    area_uniao = area_box + area_boxes - area_intersecao

    # 5. IoU
    return area_intersecao / area_uniao

"""6.2 Implementação da Função manual_nms"""

def manual_nms(boxes, scores, iou_threshold=0.45):
    """
    Nom Max Supression Manual.
    boxes: tensor de coordenadas
    scores: tensor de confianças
    iou_threshold: o limiar de sobreposição (ex: 0.45)
    """
    # Lista para guardar os índices das caixas que vamos manter
    keep = []

    # Pegar os índices ordenados pela confiança (do maior para o menor)
    vivos = torch.argsort(scores, descending=True)

    while vivos.size(0) > 0:
        # O primeiro da lista é o que tem maior confiança
        campeao = vivos[0]
        keep.append(campeao.item())

        # Se for a última caixa/indice, paramos por aqui
        if vivos.size(0) == 1:
            break

        # Calcular IoU do que tem maior confiança com todos os outros da lista
        outros = vivos[1:]
        ious = manual_iou(boxes[campeao], boxes[outros])

        # Manter apenas os que têm IoU MENOR que o limiar
        # (se for maior, significa que é o mesmo objeto e deve ser deletado)
        mascara = ious <= iou_threshold
        vivos = outros[mascara]

    return torch.tensor(keep)

"""## 7. Inferência e Visualização
Finalmente, vamos fazer o modelo detectar os objetos e mostrar o resultado na imagem.
"""

def detectar(caminho_img, modelo, class_names, device,
             score_threshold=0.25, iou_threshold=0.45,
             img_size=640, max_deteccoes=100):

    """
    Etapas da detecção de objetos:

    1. Pré-processamento da imagem
    2. Inferência com o modelo
    3. Decodificação das saídas
    4. Filtragem por confiança
    5. Aplicação de NMS
    6. Conversão para coordenadas originais
    7. Visualização dos resultados
    """
    print(f"\nProcessando: {caminho_img}")

    # 1. Pré-processamento
    img_orig, tensor, escala, ox, oy = preprocessar(caminho_img, img_size)
    tensor = tensor.to(device)

    # 2. Inferência
    modelo.eval()
    with torch.no_grad():
        outputs = modelo(tensor)

    # 3. Decodificação
    caixas, classes = decodificar_saidas(outputs, img_size, device)

    # 4. Filtragem por score de confiança
    scores_max, classes_idx = classes.max(dim=1)
    mascara = scores_max >= score_threshold
    caixas      = caixas[mascara]
    scores_max  = scores_max[mascara]
    classes_idx = classes_idx[mascara]

    print(f"  Detecções antes do NMS: {len(caixas)}")

    # Caso não haja detecções:
    if len(caixas) == 0:
        print("  Nenhum objeto detectado.")
        plt.figure(figsize=(10, 8))
        plt.imshow(img_orig)
        plt.axis('off')
        plt.title("Nenhum objeto detectado")
        plt.show()
        return

    # 5. NMS por classe (aplica NMS separadamente para cada classe)
    keep_final = []
    for cls in classes_idx.unique():
      # Seleciona apenas caixas dessa classe
        mascara_cls = classes_idx == cls
        idx_cls     = mascara_cls.nonzero(as_tuple=True)[0]
        # Aplica NMS
        keep_cls    = manual_nms(
            caixas[idx_cls], scores_max[idx_cls], iou_threshold
        )
        # Guarda índices das caixas mantidas
        keep_final.append(idx_cls[keep_cls])

    keep_final  = torch.cat(keep_final)
    # Ordena por score e limita número máximo de detecções
    ordem       = scores_max[keep_final].argsort(descending=True)[:max_deteccoes]
    keep_final  = keep_final[ordem]

    caixas_finais  = caixas[keep_final]
    scores_finais  = scores_max[keep_final]
    classes_finais = classes_idx[keep_final]

    # 6. Reverter para coordenadas da imagem original
    caixas_orig = reverter_caixas(caixas_finais, escala, ox, oy, img_orig.size)

    n = len(caixas_finais)
    print(f"  Detecções após NMS: {n}")
    print(f"  Objetos detectados:")
    for i in range(n):
        nome  = class_names[classes_finais[i].item()]
        conf  = scores_finais[i].item()
        print(f"    [{i+1:2d}] {nome:20s}  confiança: {conf:.3f}")

    # 7. Visualização
    # Desenha caixas e labels na imagem original
    img_draw = img_orig.copy()
    draw     = ImageDraw.Draw(img_draw)
    # Tenta usar uma fonte melhor
    try:
        font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 14)
    except:
        font = ImageFont.load_default()

    # Espessura da caixa proporcional ao tamanho da imagem
    espessura = max(2, (img_orig.size[0] + img_orig.size[1]) // 500)

    for i in range(n):
        x1, y1, x2, y2 = caixas_orig[i].cpu().tolist()
        cls_id = classes_finais[i].item()
        score  = scores_finais[i].item()
        nome   = class_names[cls_id]
        cor    = CORES[cls_id]

        # Bounding box
        for t in range(espessura):
            draw.rectangle([x1+t, y1+t, x2-t, y2-t], outline=cor)

        # Label
        label = f"{nome}: {score:.2f}"
        bbox_txt = draw.textbbox((x1, y1), label, font=font)
        draw.rectangle(bbox_txt, fill=cor)
        draw.text((x1, y1), label, fill=(255, 255, 255), font=font)

    # Exibição da imagem final
    plt.figure(figsize=(12, 10))
    plt.imshow(img_draw)
    plt.axis('off')
    plt.title(f"{n} objeto(s) detectado(s) — score≥{score_threshold}, IoU≤{iou_threshold}")
    plt.tight_layout()
    plt.show()

    return caixas_orig, scores_finais, classes_finais

"""## 8. Teste para todas as Imagens"""

# 1. Defina a pasta de imagens (já dentro do repositório clonado)
pasta_imagens = "images"
# 2. Lista todos os arquivos que são imagens (.jpg, .png, etc)
extensoes_validas = ('.jpg', '.jpeg', '.png', '.bmp')
arquivos = [f for f in os.listdir(pasta_imagens) if f.lower().endswith(extensoes_validas)]

print(f"Foram encontradas {len(arquivos)} imagens para processar.")

# 3. Loop para percorrer cada imagem
for nome_arquivo in arquivos:
    caminho_completo = os.path.join(pasta_imagens, nome_arquivo)

    print(f"\n" + "="*50)
    print(f"PROCESSANDO: {nome_arquivo}")
    print("="*50)

    # Executa a detecção (usando as funções que criamos anteriormente)
    try:
        detectar(
            caminho_completo,
            modelo,
            class_names,
            device,
            # Aqui, podemos ir ajustando conforme nossa preferencia
            score_threshold=0.25,
            iou_threshold=0.45
        )
    except Exception as e:
        print(f"Erro ao processar {nome_arquivo}: {e}")

print("\n--- Processamento concluído! ---")

"""## 9. Comparação: Efeito dos Limiares de NMS e IoU
Aqui vamos testar diferentes valores para os limiares de NMS e Iou e observar qual é o impacto gerado das detecções de todas as imagens.

"""

import textwrap
import os
import matplotlib.pyplot as plt
from PIL import ImageDraw, ImageFont


# Comparação dos limiares (thresholds)

# Objetivo:
# Avaliar como diferentes valores de:
# - score_threshold (confiança mínima)
# - iou_threshold (NMS)
# afetam o número e a qualidade das detecções
configs = [
    {"score_threshold": 0.10, "iou_threshold": 0.30, "desc": "Confiança baixa, IoU baixo - Confiança = 0.10 e IoU = 0.30"},
    {"score_threshold": 0.25, "iou_threshold": 0.45, "desc": "Configuração padrão YOLOv8 - Confiança = 0.25 e IoU = 0.45"},
    {"score_threshold": 0.50, "iou_threshold": 0.60, "desc": "Confiança alta, IoU alto - Confiança = 0.50 e IoU = 0.60"},
    {"score_threshold": 0.70, "iou_threshold": 0.45, "desc": "Confiança muito alta - Confiança = 0.70 e IoU = 0.45"},
]

# Caminho das pastas das imagens
pasta_imagens = "images"

# Lista arquivos de imagem válidos
extensoes = ('.jpg', '.jpeg', '.png')
arquivos = [f for f in os.listdir(pasta_imagens) if f.lower().endswith(extensoes)]

print(f"Iniciando comparação sistemática para {len(arquivos)} imagens...\n")

# Loop principal: percorre cada imagem
for nome_arquivo in arquivos:
    caminho_imagem = os.path.join(pasta_imagens, nome_arquivo)

    # Criamos uma figura (2x2) para cada imagem do diretório
    fig, axes = plt.subplots(2, 2, figsize=(16, 14))

    for ax, cfg in zip(axes.flat, configs):
        # Pré-processamento
        img_orig, tensor, escala, ox, oy = preprocessar(caminho_imagem)
        tensor = tensor.to(device)

        with torch.no_grad():
            outputs = modelo(tensor)

        # Decodificação e filtros iniciais
        caixas, classes = decodificar_saidas(outputs, 640, device)
        scores_max, classes_idx = classes.max(dim=1)

        # Filtro de Confiança (Score Threshold)
        mascara = scores_max >= cfg["score_threshold"]
        caixas = caixas[mascara]
        scores_max = scores_max[mascara]
        classes_idx = classes_idx[mascara]

        if len(caixas) > 0:
            keep_final = []
            # Aplica o NMS para cada classe
            for cls in classes_idx.unique():
                m = classes_idx == cls
                idx = m.nonzero(as_tuple=True)[0]

                keep = manual_nms(caixas[idx], scores_max[idx], cfg["iou_threshold"])
                keep_final.append(idx[keep])

            keep_final = torch.cat(keep_final)
            caixas_finais = caixas[keep_final]
            scores_finais = scores_max[keep_final]
            classes_finais = classes_idx[keep_final]

            # Ajusta as caixas para o tamanho original da foto
            caixas_orig = reverter_caixas(caixas_finais, escala, ox, oy, img_orig.size)

            img_draw = img_orig.copy()
            draw = ImageDraw.Draw(img_draw)

            try:
                font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 13)
            except:
                font = ImageFont.load_default()

            # Resultados
            for i in range(len(caixas_finais)):
                coords = caixas_orig[i].cpu().tolist()
                cls_id = classes_finais[i].item()
                cor = CORES[cls_id]
                label = f"{class_names[cls_id]}: {scores_finais[i]:.2f}"
                draw.rectangle(coords, outline=cor, width=3)
                draw.text((coords[0]+2, coords[1]+2), label, fill=cor, font=font)

            num_detecções = len(caixas_finais)
        else:
            img_draw = img_orig
            num_detecções = 0

        ax.imshow(img_draw)
        ax.axis('off')

        # Ajuste da fonte e quebra de página
        titulo_texto = f"{cfg['desc']} ({num_detecções} detecções)"

        titulo_formatado = textwrap.fill(titulo_texto, width=40)

        ax.set_title(titulo_formatado, fontsize=25, pad=10)

    plt.suptitle("Efeito dos Limiares de Confiança e IoU", fontsize=25, fontweight='bold', y=1.02)
    plt.tight_layout(h_pad=3.0)
    plt.show()

# Comparação dos limiares (idêntico ao de cima), mas para uma única imagem
configs = [
    {"score_threshold": 0.10, "iou_threshold": 0.30, "desc": "Confiança baixa, IoU baixo - Confiança = 0.10 e IoU = 0.30"},
    {"score_threshold": 0.25, "iou_threshold": 0.45, "desc": "Configuração padrão YOLOv8 - Confiança = 0.25 e IoU = 0.45"},
    {"score_threshold": 0.50, "iou_threshold": 0.60, "desc": "Confiança alta, IoU alto - Confiança = 0.50 e IoU = 0.60 "},
    {"score_threshold": 0.70, "iou_threshold": 0.45, "desc": "Confiança muito alta - Confiança = 0.70 e IoU = 0.45"},
]

IMAGEM_TESTE = "images/dog2.jpg"

fig, axes = plt.subplots(2, 2, figsize=(16, 14))

for ax, cfg in zip(axes.flat, configs):
    img_orig, tensor, escala, ox, oy = preprocessar(IMAGEM_TESTE)
    tensor = tensor.to(device)

    with torch.no_grad():
        outputs = modelo(tensor)

    caixas, classes = decodificar_saidas(outputs, 640, device)
    scores_max, classes_idx = classes.max(dim=1)
    mascara = scores_max >= cfg["score_threshold"]
    caixas = caixas[mascara]
    scores_max = scores_max[mascara]
    classes_idx = classes_idx[mascara]

    if len(caixas) > 0:
        keep_final = []
        for cls in classes_idx.unique():
            m = classes_idx == cls
            idx = m.nonzero(as_tuple=True)[0]
            keep = manual_nms(caixas[idx], scores_max[idx], cfg["iou_threshold"])
            keep_final.append(idx[keep])
        keep_final = torch.cat(keep_final)
        caixas_finais = caixas[keep_final]
        scores_finais = scores_max[keep_final]
        classes_finais = classes_idx[keep_final]
        caixas_orig = reverter_caixas(caixas_finais, escala, ox, oy, img_orig.size)

        img_draw = img_orig.copy()
        draw = ImageDraw.Draw(img_draw)
        try:
            font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 13)
        except:
            font = ImageFont.load_default()

        for i in range(len(caixas_finais)):
            x1, y1, x2, y2 = caixas_orig[i].cpu().tolist()
            cls_id = classes_finais[i].item()
            cor = CORES[cls_id]
            label = f"{class_names[cls_id]}: {scores_finais[i]:.2f}"
            draw.rectangle([x1, y1, x2, y2], outline=cor, width=2)
            draw.text((x1+2, y1+2), label, fill=cor, font=font)
        n = len(caixas_finais)
    else:
        img_draw = img_orig
        n = 0

    ax.imshow(img_draw)
    ax.axis('off')

    # --- AJUSTE DA FONTE E QUEBRA DE LINHA ---
    # Criamos a string do título
    titulo_texto = f"{cfg['desc']} ({n} detecções)"

    # textwrap.fill divide o texto em linhas de no máximo 40 caracteres
    titulo_formatado = textwrap.fill(titulo_texto, width=40)

    # Aumentamos o fontsize para 11 ou 12 e usamos o título formatado
    ax.set_title(titulo_formatado, fontsize=25, pad=10)


plt.suptitle("Efeito dos Limiares de Confiança e IoU", fontsize=25, fontweight='bold', y=1.02)
plt.tight_layout(h_pad=3.0) # h_pad aumenta o espaço vertical entre os subplots
plt.show()

"""## 10. Verificação da Arquitetura

Para finalizar, o chunck abaixo mostra um resumo da arquitetura implementada, incluindo a quantidade de parâmetros por bloco (backbone, neck e head), permitindo verificar se a estrutura do modelo está consistente com o YOLOv8-nano. Essa análise também permite validar a implementação manual foi adequada.
"""

# Resumo da arquitetura do modelo

# Total de parâmetros do modelo
total_params = sum(p.numel() for p in modelo.parameters())

# Parâmetros que são treináveis
treinaveis   = sum(p.numel() for p in modelo.parameters() if p.requires_grad)

print("=" * 60)
print("ARQUITETURA YOLOv8-nano (implementação manual)")
print("=" * 60)

print("\n[ BACKBONE ]")
for i, layer in enumerate(modelo.model):
    # Conta quantos parâmetros existem nessa camada
    n = sum(p.numel() for p in layer.parameters())
    # Exibe índice, tipo da camada e número de parâmetros
    print(f"  Layer {i:2d}: {type(layer).__name__:10s}  params: {n:,}")

print("\n[ NECK ]")
for nome, mod in [
    ('up1 (Upsample 20->40)', modelo.up1),
    ('c2f_p4_td',             modelo.c2f_p4_td),
    ('up2 (Upsample 40->80)', modelo.up2),
    ('c2f_p3_td',             modelo.c2f_p3_td),
    ('down1 (Conv 80->40)',   modelo.down1),
    ('c2f_p4_bu',             modelo.c2f_p4_bu),
    ('down2 (Conv 40->20)',   modelo.down2),
    ('c2f_p5_bu',             modelo.c2f_p5_bu),
]:
    n = sum(p.numel() for p in mod.parameters())
    print(f"  {nome:30s}  params: {n:,}")

print("\n[ HEAD ]")
print(f"  DetectHead (3 escalas: 80x80, 40x40, 20x20)")
n = sum(p.numel() for p in modelo.head.parameters())
print(f"  params: {n:,}")

print("\n" + "=" * 60)
print(f"  Total de parâmetros:      {total_params:,}")
print(f"  Parâmetros treináveis:    {treinaveis:,}")
print("=" * 60)

"""Note que o modelo apresentou aproximadamente 3,1 milhões de parâmetros, valor compatível com a arquitetura YOLOv8-nano, indicando que a implementação está adequada.

## 11. Análise Gráfica de Limiares
Abaixo, é apresentado gráficos comparando o número de detecções nas imagens com os limiares de confiança e de IoU. A comparação foi feita para 4 principais imagens incluídas e detalhadas no relatório, no entanto, pode ser adaptado para qualquer outra imagem contida no repositório.
"""

# Análise Gráfica de Limiares

import numpy as np
import matplotlib.pyplot as plt
import torch

IMAGENS_TESTE = [
    "images/cat.jpg",
    "images/amigos.jpg",
   # "images/nozes.jpg",
    "images/food.jpg",
    "images/paulista.png",
]

score_thresholds = np.round(np.arange(0.05, 0.85, 0.10), 2)  # 0.05 … 0.75
iou_thresholds   = np.round(np.arange(0.10, 1.00, 0.10), 2)  # 0.10 … 0.90

SCORE_FIXO = 0.25
IOU_FIXO   = 0.45


def contar_deteccoes(imagem_path, score_thr, iou_thr):
    img_orig, tensor, escala, ox, oy = preprocessar(imagem_path)
    tensor = tensor.to(device)
    with torch.no_grad():
        outputs = modelo(tensor)
    caixas, classes = decodificar_saidas(outputs, 640, device)
    scores_max, classes_idx = classes.max(dim=1)
    mascara     = scores_max >= score_thr
    caixas      = caixas[mascara]
    scores_max  = scores_max[mascara]
    classes_idx = classes_idx[mascara]
    if len(caixas) == 0:
        return 0
    keep_final = []
    for cls in classes_idx.unique():
        m   = classes_idx == cls
        idx = m.nonzero(as_tuple=True)[0]
        keep = manual_nms(caixas[idx], scores_max[idx], iou_thr)
        keep_final.append(idx[keep])
    return len(torch.cat(keep_final))


def yticks_inteiros(ax, valores):
    vmin, vmax = int(min(valores)), int(max(valores))
    total = vmax - vmin
    passo = max(1, round(total / 10))
    ax.set_yticks(range(vmin, vmax + 1, passo))


for img_path in IMAGENS_TESTE:
    nome = img_path.split("/")[-1]

    det_score = [contar_deteccoes(img_path, s, IOU_FIXO)   for s in score_thresholds]
    det_iou   = [contar_deteccoes(img_path, SCORE_FIXO, i) for i in iou_thresholds]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle(f"Análise de Limiares – {nome}", fontsize=14, fontweight="bold")

    # Gráfico 01
    ax1.plot(score_thresholds, det_score, "o-", color="steelblue", linewidth=2, markersize=6)
    ax1.axvline(SCORE_FIXO, color="red", linestyle="--", label=f"Padrão = {SCORE_FIXO}")
    ax1.set_title(f"Limiar de Confiança vs Detecções (IoU fixo = {IOU_FIXO})")
    ax1.set_xlabel("Limiar de Confiança")
    ax1.set_ylabel("Núm. Detecções")
    ax1.set_xticks(score_thresholds)
    ax1.set_xticklabels([f"{v:.2f}" for v in score_thresholds], rotation=45, ha="right")
    yticks_inteiros(ax1, det_score)
    ax1.legend()
    ax1.grid(True)

    # Gráfico 2
    ax2.plot(iou_thresholds, det_iou, "s-", color="darkorange", linewidth=2, markersize=6)
    ax2.axvline(IOU_FIXO, color="red", linestyle="--", label=f"Padrão = {IOU_FIXO}")
    ax2.set_title(f"Limiar de IoU vs Detecções (Score fixo = {SCORE_FIXO})")
    ax2.set_xlabel("Limiar de IoU")
    ax2.set_ylabel("Núm. Detecções")
    ax2.set_xticks(iou_thresholds)
    ax2.set_xticklabels([f"{v:.1f}" for v in iou_thresholds], rotation=45, ha="right")
    yticks_inteiros(ax2, det_iou)
    ax2.legend()
    ax2.grid(True)

    plt.tight_layout()
    plt.show()